# Font
font_family      ShureTechMono Nerd Font
font_size        12

# Window
window_padding_width 8
hide_window_decorations yes

# Cursor
cursor_trail            3
cursor_trail_decay      0.1 0.4

# Tab bar
tab_bar_edge            top
tab_bar_style           fade
tab_fade                0 1
tab_bar_min_tabs        1
tab_title_template      " {index}: {title} "
active_tab_font_style   bold
inactive_tab_font_style normal

# URL handling
open_url_with default
url_style curly
detect_urls yes

include colors.conf
